/* Creating the warehouse*/
CREATE OR REPLACE WAREHOUSE NYC_TAXI_WH
WITH
    WAREHOUSE_SIZE = 'MEDIUM'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

/*Creating the DATABASE*/
CREATE OR REPLACE DATABASE NYC_TAXI_DB;

/*Creating the Schemas*/
CREATE OR REPLACE SCHEMA RAW;
CREATE OR REPLACE SCHEMA STAGING;
CREATE OR REPLACE SCHEMA FINAL;

/* Set default context*/
USE WAREHOUSE NYC_TAXI_WH;
USE DATABASE NYC_TAXI_DB;
USE SCHEMA RAW;
